version: '3'
services:
  first_prod:
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
      - 8000
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - first_prod