version: '3'
services:
  first:
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn main:app --host 0.0.0.0 --port 5000
    expose:
      - 5000
    ports:
      - 5000:5000